export const ACTION_TYPES = {
    CHANGE_FIELD: 'CHANGE_FIELD',
    TRY_SIGNUP: 'TRY_SIGNUP',
    SIGN_UP_FAIL: 'SIGNUP_FAIL',
    SIGN_UP_SUCCESS: 'SIGNUP_SUCCESS',
    TRY_LOGIN: 'TRY_LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL'
};